#!/bin/bash

JOBS=${JOBS:-24}           # 24
SAT=kissat                 # kissat
CERT=grat                  # grat
MINOR_HEAP=2G              # 2G
KEEP=0                     # 0
FORK=1                     # 1
CARRY_CONSTRAINT=0         # 0
REWRITING=1                # 1
REWRITING_AREP=${REWRITING_AREP:-1}           # 1
REWRITING_IMP=${REWRITING_IMP:-1}             # 1
SLICING_ESPEC=1            # 1
VARS_CACHE_IN_REWRITING=1  # 1
DEBUG=0                    # 0
TMPDIR=${TMPDIR:-./tmp}    # ./tmp
LOGDIR=${LOGDIR:-./logs}   # ./logs
COQCRYPTOLINE=./_build/default/coqcryptoline.exe

FLAGS=${FLAGS:-}
FLAGS+=" -jobs ${JOBS}"
FLAGS+=" -sat_solver ${SAT}"
FLAGS+=" -sat_cert ${CERT}"
if [[ ${CARRY_CONSTRAINT} == 0 ]]; then
  FLAGS+=" -no_carry_constraint"
fi
if [[ ${FORK} == 1 ]]; then
  FLAGS+=" -fork"
fi
if [[ ${REWRITING} == 0 ]]; then
  FLAGS+=" -disable_rewriting"
fi
if [[ ${KEEP} == 1 ]]; then
  FLAGS+=" -keep"
fi
if [[ ${DEBUG} == 1 ]]; then
  FLAGS+=" -debug"
fi
if [[ ${VARS_CACHE_IN_REWRITING} == 0 ]]; then
  FLAGS+=" -disable_vars_cache_in_rewriting"
fi
if [[ ${REWRITING_AREP} == 0 ]]; then
  FLAGS+=" -disable_rewriting_arep"
else
  FLAGS+=" -enable_rewriting_arep"
fi
if [[ ${REWRITING_IMP} == 0 ]]; then
  FLAGS+=" -disable_rewriting_imp"
else
  FLAGS+=" -enable_rewriting_imp"
fi
if [[ ${SLICING_ESPEC} == 0 ]]; then
  FLAGS+=" -disable_slicing_espec"
else
  FLAGS+=" -enable_slicing_espec"
fi
FLAGS+=" -tmpdir ${TMPDIR}"

if [[ -f ${1} ]]; then
  runlog=`basename ${1}`
  runlog=${runlog/.cl/}
  if [[ ${FORK} == 1 ]]; then
    forkstr="_fork"
  else
    forkstr="_lwt"
  fi
  debuglog=${LOGDIR}/${runlog}_s${MINOR_HEAP}_${SAT}_${CERT}_ramfs_jobs${JOBS}${forkstr}_debug.log
  runlog=${LOGDIR}/${runlog}_s${MINOR_HEAP}_${SAT}_${CERT}_ramfs_jobs${JOBS}${forkstr}_run.log

  mkdir -p ${TMPDIR}
  mkdir -p ${LOGDIR}

  rm -f ${debuglog} ${runlog}

  OCAMLRUNPARAM=s=${MINOR_HEAP} \
    ${COQCRYPTOLINE} -v ${FLAGS} -o ${debuglog} ${1} | tee ${runlog}
fi
