#!/bin/bash

JOBS=2                     # 2
SAT=kissat                 # kissat
CERT=grat                  # grat
MINOR_HEAP=2G              # 2G
KEEP=0                     # 0
FORK=1                     # 1
CARRY_CONSTRAINT=0         # 0
REWRITING=1                # 1
VARS_CACHE_IN_REWRITING=1  # 1
DEBUG=1                    # 0
TMPDIR=.                   # .
LOGDIR=logs                # logs

FLAGS=
FLAGS+="-jobs ${JOBS}"
FLAGS+=" -sat_solver ${SAT}"
FLAGS+=" -sat_cert ${CERT}"
if [[ ${CARRY_CONSTRAINT} == 0 ]]; then
  FLAGS+=" -no_carry_constraint"
fi
if [[ ${FORK} == 1 ]]; then
  FLAGS+=" -fork"
fi
if [[ ${REWRITING} == 0 ]]; then
  FLAGS+=" -disable_rewriting"
fi
if [[ ${KEEP} == 1 ]]; then
  FLAGS+=" -keep"
fi
if [[ ${DEBUG} == 1 ]]; then
  FLAGS+=" -debug"
fi
if [[ ${VARS_CACHE_IN_REWRITING} == 0 ]]; then
  FLAGS+=" -disable_vars_cache_in_rewriting"
fi
FLAGS+=" -tmpdir ${TMPDIR}"

if [[ -f ${1} ]]; then
  runlog=`basename ${1}`
  runlog=${runlog/.cl/}
  if [[ ${FORK} == 1 ]]; then
    forkstr="_fork"
  else
    forkstr="_lwt"
  fi
  debuglog=${runlog}_s${MINOR_HEAP}_${SAT}_${CERT}_ramfs_jobs${JOBS}${forkstr}_debug.log
  runlog=${runlog}_s${MINOR_HEAP}_${SAT}_${CERT}_ramfs_jobs${JOBS}${forkstr}.log

  rm -f ${debuglog}
  rm -f ${runlog}

  mkdir -p ${LOGDIR}

  OCAMLRUNPARAM=s=${MINOR_HEAP} \
    ./_build/default/coqcryptoline.exe -v ${FLAGS} \
    -o ${LOGDIR}/${debuglog} ${1} \
    &> ${LOGDIR}/${runlog}
fi
